### ISSUE TITLE
FR: Support for Existing Fieldtype Icons

### ISSUE THREAD

**Issue by mikemartin** [AddonFoundry/flexible-forms#1]
I've created a custom fieldtype with my own Icon and would like that same icon to appear in FlexibleForm list. But it looks like the Fieldtype's Icon is not used and replaced with a set of custom icons instead.

Could you add support or a config option to use the existing [Fieldtype Icons](https://statamic.dev/extending/fieldtypes#fieldtype-icon) instead?

**Comment by AddonFoundry** [comment]
@mikemartin Flexible Forms now uses Statamic's default fieldtype icons and has support for custom fieldtypes and fieldtype icons as of version 1.2.4. Thanks for the feature request!

**Comment by mikemartin** [comment]
Great! Thank you!
