### ISSUE TITLE
FR: Make Available fields sidebar sticky

### ISSUE THREAD

**Issue by mikemartin** [AddonFoundry/flexible-forms#2]
Could you make the the Available Fields sidebar sticky for editing long forms? I've noticed when editing a long form, the field "Drop zone" target is too far down the page. 

<img width="1186" alt="Screenshot 2024-07-16 at 7 51 12 PM" src="https://github.com/user-attachments/assets/612f404c-8d43-4900-9db5-365eb2677fbd">

**Comment by AddonFoundry** [comment]
Thanks @mikemartin, really appreciate the feedback! This has been added in release [1.1.5](https://github.com/AddonFoundry/flexible-forms/releases/tag/1.1.5) along with an add field icon to make it easier for users to add fields to longer forms.
