### ISSUE TITLE
Sections support

### ISSUE THREAD

**Issue by mikemartin** [AddonFoundry/flexible-forms#3]
Hey there!
I understand that flexible forms was designed for simple use cases such as contact forms, but have you considered adding support for Sections?

**Comment by freshface** [comment]
Having the same issue.

**Comment by AddonFoundry** [comment]
@mikemartin @freshface thanks for the feedback, we are working on adding support for sections now. We are aiming to release this in the next version by end of next week. Thanks!

**Comment by AddonFoundry** [comment]
@mikemartin @freshface sections support is now available in version 1.2.6. Please let us know if there are any issues or if you have any further feature requests!

**Comment by mikemartin** [comment]
Wahoo! Client will be stoked. Thank you 🙏
